name: Deploy WhatTodo app to appstore
on:
  workflow_dispatch:

jobs:
  deployIos:
    runs-on: macos-latest
    env:
      ASC_JSON_KEY: ${{ secrets.ASC_JSON_KEY }}
      FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD: ${{ secrets.APPLE_PASSWORD }}
    steps:
      - name: ⬇️ Checkout repository
        uses: actions/checkout@v3
      - name: ⚙️ Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.22.0"
          channel: 'stable'
          cache: true
        id: flutter
      - name: Setup Fastlane
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.3"
          bundler-cache: true
          working-directory: ios
      - name: Setup app store connect
        run: echo "$ASC_JSON_KEY" >> ./ios/fastlane/store.json
      - name: Build and Deploy to TestFlight
        env:
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
          MATCH_GIT_BASIC_AUTHORIZATION: ${{ secrets.MATCH_GIT_BASIC_AUTHORIZATION }}
        run: |
          cd ./ios
          bundle exec fastlane ios beta
